openapi: 3.0.0
paths:
  /tickets:
    post:
      operationId: createTicket
      parameters: []
      requestBody:
        required: true
        description: body:TicketDTO
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketDTO"
      responses:
        "200":
          description: Sends back a TicketDTO
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketDTO"
    get:
      operationId: getAll
      parameters: []
      responses:
        "200":
          description: creates ticket Objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketDTO"
info:
  title: TicketTool
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    TicketDTO:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
        beschreibung:
          type: string
      required:
        - name
        - date
        - beschreibung
