openapi: 3.0.0
paths:
  /tickets:
    post:
      operationId: createTicket
      parameters: []
      responses:
        "201":
          description: ""
    get:
      operationId: getAll
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: TicketTool
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas: {}
