openapi: 3.0.0
paths:
  /:
    get:
      operationId: getHello
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: TicketTool
  description: ""
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas: {}
